### ISSUE TITLE
some item show wrong

### ISSUE THREAD

**Issue by D0lores** [SainteCroquette/medianXLitemChecker#1]
![image](https://user-images.githubusercontent.com/56717078/128332674-801d897c-d78f-46de-9577-db0aca6e020e.png)

**Comment by SainteCroquette** [comment]
Yeah i believe the regex checking for "Elemental Resists" match for "Maximum elemental resists"
Can you send me the link of your char which have this item?
I also noticed that + 0 rolls (which doest show up in text then) is ignored. gonna fix that after i finish refactoring the code

**Comment by SainteCroquette** [comment]
Okay i found the issue and i have fixed it ! thanks for signaling :)
