### ISSUE TITLE
var range display error

### ISSUE THREAD

**Issue by D0lores** [SainteCroquette/medianXLitemChecker#2]
![Snipaste_2021-08-10_09-11-30](https://user-images.githubusercontent.com/56717078/128793435-4f8032e7-0964-462e-8c17-28628f97feb6.png)

the druid skill lvl 0%

and notarmory link for test : [click me](https://tsw.vn.cz/acc/char.php?name=gb_armor)

**Comment by SainteCroquette** [comment]
That's not an error that's how it compute the value :
- (x - y) [attribute] where x is the minimum and y the maximum
- z is the actual value you got (1 in your case)
Percentage = (z - x) / (y - x) * 100

if x = 1, y = 2, z = 1 we have:
(1 - 1) / (2 - 1) = 0 / 1 = 0

This the reason why it is shown as a 0% as this is the lowest value possible. In your case  it will be either 0% or 100% on that attribute, there's no middle values.
